[project]
name = "ventureai"
version = "0.1.0"
description = "Next Gen AI Agent for Stock Market Analysis and Guidance"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[google-genai]>=0.3.25",
    "langgraph>=0.4.8",
    "streamlit>=1.45.1",
    "yfinance>=0.2.61",
]

[tool.basedpyright]
reportUnusedCallResult = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportMissingTypeArgument = "none"
reportAny = "none"
useLibraryCodeForTypes = true
