[project]
name = "ventureai"
version = "0.1.0"
description = "Next Gen AI Agent for Stock Market Analysis and Guidance"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.45.1",
]

[tool.basedpyright]
reportUnusedCallResult = "none"
reportUnknownMemberType = "none"
reportUnknownVariableType = "none"
reportMissingTypeArgument = "none"
reportAny = "none"
